import type { Metadata } from "next";
import "./globals.css";
import { ThemeInitializer } from "@/inits/theme-initializer";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import { GeistPixelSquare } from "geist/font/pixel";
import MouseMoveEffect from "@/components/move-mosue-effect";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${GeistSans.variable} ${GeistMono.variable} ${GeistPixelSquare.variable}`}
    >
      <body
        className={`${GeistSans.variable} ${GeistMono.variable} antialiased`}
      >
        <ThemeInitializer />
        {/* <MouseMoveEffect /> */}
        {/* <BlocksOverlay /> */}
        <div className="relative z-10">{children}</div>
      </body>
    </html>
  );
}
